### ISSUE TITLE
Error when trying to serve

### ISSUE THREAD

**Issue by TheDevelolper** [omnidan/redux-undo-boilerplate#5]
When trying to serve I get the following errors (note I have removed file paths from the error:

`PS> ng serve --port 4201 -o

@angular/compiler-cli@4.4.5 requires typescript@'>=2.1.0 <2.4.0' but 2.5.3 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.1.0 <2.4.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".

Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (c:\ ... \ngrx-undo\redux-undo-boilerplate\node_modules\@angular\cli\tasks\serve.js:51:63)
    at check_port_1.checkPort.then.port (c:\ ... \ngrx-undo\redux-undo-boilerplate\node_modules\@angular\cli\commands\serve.js:12
1:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

Any help would be appreciated.

**Comment by omnidan** [comment]
@KiransHub this boilerplate uses React, not Angular. You cannot run it via `ng`. If you want to try out redux-undo, do the following steps to run this React & Redux app:

```
npm install
npm run dev
```

If you want to use redux-undo with Angular, you will have to use a different boilerplate or implement it yourself :(

**Comment by omnidan** [comment]
Feel free to reopen this issue if anything is still unclear, or open an issue on the redux-undo project if you're having troubles getting redux-undo running with Angular.
